name: "Lint"

on:
  push:
    paths:
      - "*.go"
  pull_request:
    branches:
      - master
jobs:
  link:
    runs-on: ubuntu-latest
    name: "lint"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
