name: "Release:Test"
on:
  push:
    tags:
      - 'test/**'
permissions:
  contents: write

jobs:
  release-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Define the plugin
        id: pluginID
        run: |
          echo "fromJSON(${{ github.event.ref }})"
