name: "Release:Test"
on:
  push:
    tags:
      - 'test/**'
permissions:
  contents: write

jobs:
  release-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Define the plugin
        id: pluginID
        run: |
          TAG=$(echo '${{ github.event.ref }}' | awk -F "/" '{print $NF}')
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - name: Test
        run: |
          echo "plugin/${{ steps.pluginID.outputs.plugin }}/.release_notes/${{ steps.pluginID.outputs.tag }}.md"
